version: '3.1'
services:
  stats-server:
    build:
      context: ./stat/stat-server
      dockerfile: Dockerfile
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  main-service:
    build:
      context: ./main-service
      dockerfile: Dockerfile
    container_name: main-service
    ports:
      - "8080:8080"
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
