DROP TABLE IF EXISTS hit;

CREATE TABLE IF NOT EXISTS hit
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       varchar2(20),
    uri       varchar2(20),
    ip        varchar2(20),
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_hit primary key (id)
)